export const LAYOUT_CONFIG = {
  MIN_WIDTH: 320,
  MIN_DESKTOP_HEIGHT: 550,
  ARTWORK_MAX_SIZE :260,
  EMBED_PLAYER_MIN_HEIGHT : 120,
  PLAY_ICON_SIZE :44,
  TRACK_TITLE_MIN_HEIGHT: 28,
  RESULT_AVATAR_SIZE: 36,
} as const;